apiVersion: addons.kyma-project.io/v1alpha1
kind: ClusterAddonsConfiguration
metadata:
  name: custom-addons
  finalizers:
  - addons.kyma-project.io
spec:
  repositories:
  - url: "git::ssh://git@github.com/BioMedTech/kyma-addons.git//addons/index.yaml?sshkey={key}"
    secretRef:
      name: github-auth
      namespace: default