apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: {{ template "openid-connect.fullname" . }}
spec:
  grantTypes:
    {{- range .Values.grantTypes }}
    - {{ . }}
    {{ end -}}
  scope: {{ .Values.scope }}
  secretName: {{ template "openid-connect.fullname" . }}
  redirectUris:
    {{- range .Values.redirectUris }}
    - {{ . }}
    {{ end -}}
